name = "Goldified!"
role = "Server Staff"
email = "goldifiedd@gmail.com"
birthday = "June 20, 2009"
location = "San Fransisco, California, USA"
avatar = "./config/assets/avatars/download.png"
username = "Goldified" # <-- github user name

presentation = """
I'm Goldified (He/Him) from the US. I started moderating online communities on Discord and Minecraft servers 3 years ago while playing video games and combining both gaming & moderation together. Nowadays you can find me shaping the platform in quite recognizable companies.

During my years online & on Discord, I have had so many unique opportunities to collaborate with a variety of servers and organizations with moderation, administration, support and community management. My main idea was to ensure everyone remained a safe place for users and to create a joyful environment. You can check out servers I have taken or currently am taking part and learn about what I have done for all of these communities. You may find out the communities comes in different sizes & topics and that is what I have done throughout many years which was to go and experience other communities and grow my experience.
"""
